#Numpy

##Numpy is a Python library, was created in 2005 by Travis Oliphant
## Numpy is used for working with arrays. Numpy is short form of "Numerical Python". 50x faster than traditional python lists.

In [1]:
#importing numpy library
import numpy as np

In [2]:
arr1 =np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


###different ways to create numpy array

In [ ]:
#to create an ndarray, we can pass a list -, tuple or other array like object.

In [3]:
#create 2D array
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [4]:
#to see the dimension
print(arr3.ndim)

2


In [19]:
#create 3D array
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr4)
print(arr4.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [6]:
#numpy array indexing
arr5=np.array([1,2,3,4,5,6,7])
print(arr5[2])

3


In [9]:
print(arr5[0:3])

#using negative index
print(arr5[-3:])

[1 2 3]
[3 4 5]


In [13]:
#adding to indexing numbers
print(arr5[2]+arr5[3])

7


In [17]:
#access the element on the first row , second element
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr6)
print('2nd element on 1st row: ', arr6[0, 1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2


In [18]:
#access the element on 2nd row ,5th column
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ', arr6[1, 4])

5th element on 2nd row:  10


In [20]:
#to print element in 3d array using indexing
arr4 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr4)
print(arr4[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
#print the last element from 2nd dim
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim: ', arr6[1, -1])

In [23]:
#slice elements from index 1 to index 5 from the following array
arr7 =np.array([10,20,30,40,50,60,75])
print(arr7[1:5])

#slice elements from index 4
print(arr7[4:])


#slice elements from beginning
print(arr7[:4])

[20 30 40 50]
[50 60 75]
[10 20 30 40]


In [26]:
arr5=np.array([1,2,3,4,5,6,7])
print(arr5[-3:-1])

print(arr5[1:5:2])

#return every other element from the entire array
print(arr5[::2])

[5 6]
[2 4]
[1 3 5 7]


In [29]:
#slicing 2d array
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr6[1, 1:4])

print(arr6[0:2, 2])

print(arr6[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


##Data types in numpy

###Numpy has some extra data types, and refer to data types with one character,like i for integers, u for unsigned integers etc.

In [30]:
#create an array with data type string
arr8=np.array([1,2,3,4],dtype ='S')
print(arr8)
print(arr8.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [31]:

arr8=np.array([1,2,3,4],dtype ='i4')
print(arr8)
print(arr8.dtype)

[1 2 3 4]
int32


In [35]:
arr9 = np.array([1.1,2.1,3.1])
newarr =arr9.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


##Numpy Array Copy vs View
###The main difference between a copy and a view of an array is that the copy is a new array , and the view is just a view of the original array.

###any changes made to the  original array will affect the view

In [41]:
#make a copy , change the original array, and display both arrays:
arr5=np.array([1,2,3,4,5,6,7])
x=arr5.copy()
arr5[0] =42
print(arr5)
print(x)

[42  2  3  4  5  6  7]
[1 2 3 4 5 6 7]


In [40]:
#make a view, change the original array, and display both arrays
arr5=np.array([1,2,3,4,5,6,7])
x=arr5.view()
arr5[0] =42
print(arr5)
print(x)

[42  2  3  4  5  6  7]
[42  2  3  4  5  6  7]


#Array Shape
###The shape of an array is the number of elements in each dimension

In [45]:
#print shape of 2D array
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr6.shape)

(2, 5)


In [47]:
#convert a 1D array with 12 elements into 2D array
arr10 =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr =arr10.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##Flattening the array
###Flattenng array means converting a multidimensional array to 1D array

In [48]:
arr6=np.array([[1,2,3,4,5],[6,7,8,9,10]])
newarr=arr6.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


##Numpy array iterating
###Iterating means going through elements one by one